spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chess-ai-battle
  data:
    mongodb:
      uri: mongodb://localhost:27017/chess-ai-battle
  ai:
    openai:
      api-key: ${SECRET_API_KEY}
      chat:
        options:
          model: gpt-5-nano
  #          temperature: 1

logging:
  level:
    org.springframework.ai.chat.client.advisor: INFO
    com.github.jenkaby.chessaibattle.config.advisor: info
    com.github.jenkaby.chessaibattle.service.ReplayChessGameService: DEBUG

app:
  max-turns: 100
  black-player:
    model: gpt-5-nano
  white-player:
    model: gpt-5-nano
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
