services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  api-service:
    build:
      context: ..
      dockerfile: chess-ai-battle/Dockerfile
      args:
        SERVICE: chess-ai-battle
    restart: no
    ports:
      - "8080:80"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/chess-ai-battle
      - SERVER_PORT=80
    depends_on:
      - mongo
    profiles:
      - app

volumes:
  mongo-data:
  mongo-config:

networks:
  default:
    name: chess-ai-battle-network