name: Build and Deploy
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  UI_DIR: ui
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: ${{ env.UI_DIR }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.UI_DIR }}

      - name: Build
        run: npm run build -- --base-href=/${{ env.REPO_NAME }}/
        working-directory: ${{ env.UI_DIR }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.UI_DIR }}/dist/${{ env.UI_DIR }}/browser

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4